/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'pdontams' at '12/11/18 3:47 PM' with Gradle 2.14
 *
 * @author pdontams, @date 12/11/18 3:47 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
